server {
    listen      127.0.1.1:8080;
    listen 		127.0.0.1:8082;
    server_name         local.dev dev.local;
    root                ./YoupiBanane;
    client_max_body_size  1000000000;


    index   youpi.bad_extension;
    methods        GET POST DELETE HEAD;

    location / {
        methods    GET DELETE;
        index            youpi.bad_extension;
        client_max_body_size 1000000000;
    }

    location /post_body {
        methods    POST;
        root        ./YoupiBanane/post_body;
        client_max_body_size    100;
    }

    location /directory {
        methods    GET POST;
        root             ./YoupiBanane;
        index            youpi.bad_extension;

	client_max_body_size 100000000000;
	cgi_path            ./cgi_tester;
    	cgi_ext             .bla;


    }
}
