server {
    listen 0.0.0.0:8080;
    listen 127.0.0.xx:8081;
    server_name localhost;
    root ./www;
    index index.html;
    error_page 404 /custom_404.html;

    client_max_body_size       10m;
    methods GET;
    autoindex on;

    location / {
        root ./www;
        index index.html;
    }

    location /index.html {
        methods GET;
    }


    location /images {
        root /tmp/imgs;
    }

    location / {
        return 301 http://another-site.com;
    }

    location /request{
        methods GET;
        root ./www/request;
    }

    location /usr{
        methods POST;
        root ./www/user_data;
        upload_path ./www/user_data/uploads;
    }

    location /images {
        root /tmp/imgs/;
    }

    location /private {
        root /www/secret;
        autoindex off;
    }

    location /cgi-bin {
        root ./www/cgi-scripts; # CGI script file
        methods GET POST;

        cgi_path ./cgi-bin/php-cgi; # CGI interpter 
        cgi_ext .php; #tell server which type of extention script is expected
    }

}

server {
    listen 8080;
    listen 8082;
    server_name cat.com;
    root ./www/cat;
    error_page 404 /custom_404.html;

    client_max_body_size       10m;
    methods GET POST;

}

server {
    listen 8083;
    server_name dog.com;
    root ./www/dog;
    error_page 404 /custom_404.html;
 
    client_max_body_size       10m;
    methods GET POST;

}

