server {
    listen 8080;
    server_name localhost;
    root ./www;
    index index.html;

    location / {
        methods GET POST;
    }

    location /cgi-bin {
        methods GET POST;
        cgi_pass ./cgi-bin/php-cgi;
    }
}
