server {
    listen 0.0.0.0:8080;
    listen 0.0.0.0:8081;
    server_name localhost lilou;
    root ./www;

    index index.html;
    error_page 404 /custom_404.html;
    error_page 504 /custom_504.html;
    client_max_body_size       2M;
    methods GET POST HEAD DELETE;
    autoindex on;

    location / {
        root ./www;
        methods GET HEAD;
        index index.html;
    }

    location /uploads {
        upload_path ./www/uploads;
        methods POST DELETE;
        client_max_body_size       123456;
    }

    location /test/index.html {
        methods GET;
    }

    location /redirect {
        return 301 http://another-site.com;
    }

    #location /request{
    #    methods GET;
    #    root ./www/request;
    #}

    #location /usr{
    #    methods POST;
    #    root ./www/user_data;
    #    upload_path ./www/user_data/uploads;
    #}

    #location /images {
    #    root /tmp/imgs/;
    #}

    #location /private {
    #    root /www/secret;
    #    autoindex off;
    #}

    location /cgi-bin {
        root ./www/cgi-scripts; 
        methods GET POST;

        # 核心修改：让服务器的 CGI 处理器直接去调用你虚拟环境里的 Python
        # cgi_path    /opt/hostedtoolcache/Python/3.10.20/x64/bin/python;
        cgi_path  /usr/bin/python3;
        #cgi_path ./.venv/bin/python3; 
        cgi_ext .py;
    }

    location /login {
        root ./www/login;
        index login_index.html;
        methods GET POST;
        cgi_script login.py;
        cgi_path /usr/bin/python3; #for yan's laptop setting cofig
        cgi_ext .py;
    }

    location /auth {
        root ./www/auth;      
        methods GET;               
        cgi_path /usr/bin/python3;
        cgi_ext .py;
        cgi_script auth_check.py; 
    }

    location /logout {
        root ./www/logout;
        methods POST;
        cgi_path /usr/bin/python3;
        cgi_ext .py;
        cgi_script logout.py;
    }

    location /files/ {
        root ./www/files;
        autoindex on;
    }
}

server {
    listen 8080;
    listen 8082;
    server_name cat.com;
    root ./www;
    error_page 404 /custom_404.html;

    client_max_body_size       10m;
    methods GET POST;
}

server {
    listen 8083;
    server_name dog.com;
    root ./www;
    error_page 404 /custom_404.html;
 
    client_max_body_size       10m;
    methods GET POST;

}

