server {
    listen 8080;
    server_name test.com;
    root ./docs/default;

    location / {
        root ./docs/root_path;
        index index.html;
    }

    location /images {
        root ./docs/media;
        index media.html;
    }

    location /images/icons {
        root ./docs/icons_collection;
        index icons.html;
    }

    location /api/v1 {
        root ./docs/api_old;
    }

    location /api/v1/users {
        root ./docs/api_new;
    }
}