server {
    listen 127.0.0.1:8080;
    server_name cat.com lilou.com;
    root ./www;
    error_page 404 /custom_404.html;

    index cat_index.html;
    client_max_body_size       10m;
    methods GET POST;

}

#netstat -tlnp | grep webserv